apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: {{ .Values.app.components }}
  template:
    metadata:
      name: {{ .Values.app.name }}
      labels:
        components: {{ .Values.app.components }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image }}:{{ .Values.app.imageVersion }}"
          imagePullPolicy: Always
          resources:
            limits: {{ .Values.app.limits | toYaml | nindent 16 }}
          ports:
            - containerPort: {{ .Values.app.containerPort }}
