apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.name}}-secret
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgres.db | b64enc }}
  POSTGRES_USER: {{ .Values.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
